### ISSUE TITLE
restarting pc causes issues with default channel numbers

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#48]
if i set custom default channel numbers to start at channel 1000 and disable a lot of channels, when i restart my pc the start channels reset back to 0 and all of the channels become enabled as if all the channels are reset back to defaults. like my channel settings are not persistent.

**Comment by merrychrishna** [comment]
the log is empty

**Comment by rocky4546** [comment]
Unless you can provide some details like a log on what is happening, this issue will be closed as non-discrepant since it is not reproducible.

**Comment by rocky4546** [comment]
Definitely strange.  I have fixed the ProtocolError in the log.  The startup looks like it does not know where anything is.  I need to look over your config.ini file.  Also, how are you starting Cabernet... from a service, in a cmd window, ... and if from the commandline, what is the command used.

FYI, I have run tests in Windows using the service that Cabernet installs and nothing like this is happening.  Also, you have an additional line in the log
2023-03-24 14:38:56,961-INFO:user_config Loading Configuration File: Z:\cabernet\data\config.ini
that I do not have.  Wondering if that is an indication of something you are doing.

**Comment by merrychrishna** [comment]
[config.ini.txt](https://github.com/cabernetwork/cabernet/files/11066612/config.ini.txt)

**Comment by merrychrishna** [comment]
im running it from multiple batch files and a bash file

------------------------------------------------------
START_ALL_SERVERS.bat
-------------------------------------------------------
@echo off
TITLE START_ALL_SERVERS_PERSISTENT
color 0D


:beginning

SET PID=
FOR /F "tokens=2 delims= " %%i IN ('TASKLIST ^| FIND /i "xteve.exe"') DO SET PID=%%i
IF [%PID%]==[] (

    GOTO RUN
)

SET PID=
FOR /F "tokens=2 delims= " %%i IN ('TASKLIST ^| FIND /i "xteve.exe"') DO SET PID=%%i
IF NOT [%PID%]==[] (
    GOTO beginning
)


:RUN
start /min "stopALL" cmd /c "C:\cygwin64\home\user\PlutoIPTV\stop_all_servers_startup.bat"
TIMEOUT /T 10
start /min "startALL" cmd /c "C:\cygwin64\home\user\PlutoIPTV\START_MAIN_test.bat"
echo %DATE% %TIME%      Application was not running. Restarting script.

TIMEOUT /T 190
GOTO beginning
-------------------------------------------------







START_MAIN_test.bat
--------------------------------------------------

TITLE START_MAIN_TEST
color 0B



cd C:\cygwin64\home\user\PlutoIPTV


:: start /min "START_PLEX" cmd /c "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"
:: timeout /T 5 /nobreak


start cmd /c C:\cygwin64\bin\bash --login -c  "cd ../user/PlutoIPTV; dos2unix plutotv_update_epg_test.sh"
start "START_PLUTO" cmd /c C:\cygwin64\bin\bash --login -c "cd ../user/PlutoIPTV; ./plutotv_update_epg_test.sh"
timeout /T 5 /nobreak

:: start cmd /c /min C:\cygwin64\bin\bash --login -c  "cd ../user/PlutoIPTV; dos2unix start_xteve_dizquetv_test.sh"
:: start "START_XTEVE" cmd /c /min C:\cygwin64\bin\bash --login -c "cd ../user/PlutoIPTV; ./start_xteve_dizquetv_ersatztv.sh"


start C:\cygwin64\bin\bash --login -c  "cd ../user/PlutoIPTV; dos2unix start_xteve_dizquetv_test.sh"
start "START_XTEVE_DIZQUETV_ERSATZTV" C:\cygwin64\bin\bash --login -c "cd ../user/PlutoIPTV; ./start_xteve_dizquetv_ersatztv.sh"

start C:\cygwin64\bin\bash --login -c  "cd ../user/PlutoIPTV; dos2unix start_cabernet.sh"
start "START_CABERNET" C:\cygwin64\bin\bash --login -c  "cd ../user/PlutoIPTV; ./start_cabernet.sh"

timeout /T 160 /nobreak
start firefox
start "START_EMBY" cmd /c "C:\Users\User0\AppData\Roaming\Emby-Server\system\EmbyServer.exe"
:: start cmd /c "C:\Users\User0\AppData\Roaming\Emby-Server\system\embytray.exe"


timeout /T 5 /nobreak
start "START_PLEX" cmd /c "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"
---------------------------------------------------------------------------------------


start_cabernet.sh
---------------------------------------------------------------------------------------
#!/bin/bash


C:/cygwin64/home/user/PlutoIPTV/start_cabernet.bat
-----------------------------------------------------------------------------------

start_cabernet.bat
-----------------------------------------------------------------------------------

color 0A

firefox http://localhost:6077
Z:
cd "Z:\cabernet"
:: cd Z:\TEMP\cabernet\data
call python Z:\cabernet\tvh_main.py
pause
-----------------------------------------------------------------------

**Comment by merrychrishna** [comment]
Z:\cabernet\data\config.ini is where I installedcabernet inorder to bypass
the permission errors.

**Comment by merrychrishna** [comment]
no its not in z:\TEMP\ i dont think since i uncommented that path in one of my batch files. unless i still have that path in the config.ini, im not sure. ill look at the config

**Comment by merrychrishna** [comment]
are you referring to this line i have?
--------------------------------
color 0A

firefox http://localhost:6077
Z:
cd "Z:\cabernet"
:: cd Z:\TEMP\cabernet\data
call python Z:\cabernet\tvh_main.py
pause


--------------------------------

the :: means it should be getting commented

**Comment by rocky4546** [comment]
yea, just making sure its not somewhere and you have it being used somehow.  I checked the config.ini and it looks fine.  Are you running in a cygwin64 unix environment or MSDOS/Windows?  Nothing so far indicates the issue.

**Comment by merrychrishna** [comment]
im on windows 10 and i have cygwin installed to allow me to also run linux bash files.

**Comment by merrychrishna** [comment]
but i think i did try to install cabernet to the z:/TEMP folder first . then later i uninstalled cabernet and installed to z:/cabernet

**Comment by merrychrishna** [comment]
one windows batch file calls a linux bash file which calls a windows batch file that runs cabernet from python

**Comment by merrychrishna** [comment]
and i do have the z:/TEMP folder still. maybe i should try deleting it?

![image](https://user-images.githubusercontent.com/59185469/227655843-3d846d06-ddaf-4037-8741-de22bd13ba1b.png)

**Comment by rocky4546** [comment]
well, I would try bringing up a simple CMD window and executing the call python command.  See if it will start correctly without the delete.  One major difference between windows and unix is unix forks while windows does not, so windows requires pickling.

**Comment by merrychrishna** [comment]
it wasnt rebooting that was the issue now. i just simply closed the cmd window and ran the windows batch file again and the plugin error is back without neededing to restart my pc.


C:\cygwin64\home\user\PlutoIPTV>Z:

Z:\>cd "Z:\cabernet"

Z:\cabernet>call python Z:\cabernet\tvh_main.py
2023-03-24 19:05:50,286-INFO:user_config Loading Configuration File: Z:\cabernet\data\config.ini
2023-03-24 19:05:50,596-WARNING:main #########################################
2023-03-24 19:05:50,596-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
2023-03-24 19:05:50,596-NOTICE:main Cabernet v0.9.11.00-RC1
2023-03-24 19:05:50,597-INFO:main Getting Plugins...
Traceback (most recent call last):
  File "Z:\cabernet\tvh_main.py", line 41, in <module>
    main.main(script_dir)
  File "Z:\cabernet\lib\main.py", line 136, in main
    plugins = init_plugins(config_obj)
  File "Z:\cabernet\lib\main.py", line 190, in init_plugins
    plugins = plugin_handler.PluginHandler(_config_obj)
  File "Z:\cabernet\lib\plugins\plugin_handler.py", line 45, in __init__
    self.repos.load_cabernet_repo()
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 55, in load_cabernet_repo
    self.update_plugins(repo_settings)
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 95, in update_plugins
    plugin['external'] = plugin_data['external']
KeyError: 'external'

Z:\cabernet>pause



this is all thats in the batchfile i ran just now.

--------------------------------------------------------
color 0A

firefox http://localhost:6077
Z:
cd "Z:\cabernet"
:: cd Z:\TEMP\cabernet\data
call python Z:\cabernet\tvh_main.py
pause

**Comment by rocky4546** [comment]
I saw that and have fixed in the next release.  It is associated with a plugin that is available but not installed in the plugins folder.  You should have all plugins installed, so that should not be happening.

**Comment by merrychrishna** [comment]
what evrsion was it fixed in?  im on Version: 0.9.11.00-RC1

**Comment by merrychrishna** [comment]
Microsoft Windows [Version 10.0.19045.2728]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User0>call python Z:\cabernet\tvh_main.py
2023-03-24 19:17:58,967-INFO:user_config Loading Configuration File: Z:\cabernet\data\config.ini
2023-03-24 19:17:59,280-WARNING:main #########################################
2023-03-24 19:17:59,280-WARNING:main MIT License, Copyright (C) 2021 ROCKY4546
2023-03-24 19:17:59,280-NOTICE:main Cabernet v0.9.11.00-RC1
2023-03-24 19:17:59,281-INFO:main Getting Plugins...
Traceback (most recent call last):
  File "Z:\cabernet\tvh_main.py", line 41, in <module>
    main.main(script_dir)
  File "Z:\cabernet\lib\main.py", line 136, in main
    plugins = init_plugins(config_obj)
  File "Z:\cabernet\lib\main.py", line 190, in init_plugins
    plugins = plugin_handler.PluginHandler(_config_obj)
  File "Z:\cabernet\lib\plugins\plugin_handler.py", line 45, in __init__
    self.repos.load_cabernet_repo()
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 55, in load_cabernet_repo
    self.update_plugins(repo_settings)
  File "Z:\cabernet\lib\plugins\repo_handler.py", line 95, in update_plugins
    plugin['external'] = plugin_data['external']
KeyError: 'external'

C:\Users\User0>

**Comment by merrychrishna** [comment]
deleting the plugins file only allows cabernet to run once

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/227661212-8a7470e0-ac3f-4eef-a3b6-eb50b436c735.png)

**Comment by rocky4546** [comment]
do you have the tvguide plugin installed?

**Comment by merrychrishna** [comment]
where do i look for the tv guide plugin?

**Comment by rocky4546** [comment]
it will be in the plugins_ext folder instead of the plugins folder.  Also, I have been able to reproduce the issue by removing the plugins.db file.  Plan is to test the next release and see if it is no longer present.

**Comment by merrychrishna** [comment]
oh ok sweet.  well heres what plugins i have anyway.


![image](https://user-images.githubusercontent.com/59185469/227667359-2462004e-09f7-4a25-9f63-72e951a0b438.png)

**Comment by rocky4546** [comment]
ok, so you do not have tvguide plugin. it is not used with pluto, so no big deal.  If you add daddylive, then it would be useful.  I checked and RC2 does not have the issue. Will try and release it tonight.  It will also have a few bug fixes you may be interested in.
- The channel number on the home page status was the producers channel number instead of what appeared on the channel editor.  It now displays what is on the channel editor.
- plutotv with filtering off now works, but you may see some interesting issues with timelines if you record with filtering off.  Recommend having pts resync on to reduce timeline issues when filtering is off.
- if you have not tried the new starting channel function in RC1, I recommend trying it.  it incrementally sets the channel numbers instead of an offset of the provider channel numbers.  It will only execute when it is changed in the settings area.

**Comment by merrychrishna** [comment]
sounds awesome. ill keep an eye out for th erelease. thanks.

**Comment by merrychrishna** [comment]
i see your new version showing up on github now here https://github.com/cabernetwork/cabernet/releases   but when i select to  search for ota updates in cabernet and refresh teh page to view the homescreen, no update is found.

**Comment by merrychrishna** [comment]
the new version is working great. i just tested it.  when i close the cmd prompt and start it again it works everytime now as it should and disabling filters hasnt frozen yet on the mystery science theater 3000 channel. ill try some more channels tomorrow.
